### PR TITLE
Alluo / Front end dapp / 149 Correct detail / add stroke to selector element on deposit / withdraw…

### PR DESCRIPTION
**Pull request by Dan1618**
[…al screen in farms](https://app.dework.xyz/alluo/alluo-smart-contra/view/board-6651?taskId=85a753f5-bdf6-44ae-8420-31a8af65e027)

### CODE REVIEW

**Review by 0xtuytuy — DISMISSED** [review]
image

this looks decent to me

**Comment by julabear** [comment]
Hi

I've just taken a look and the shape of the selector no longer seems to be correct. I've pasted a screenshot below of where I'm noticing this. The way the selected tab fits in the outer frame should follow the same curve, and the darker grey stroke should be 1px, and show 1px of the pale grey internal stroke before the white selected tab.

image

Correct design (shown for light version): 
image

image

**Comment by Dan1618** [comment]
@julabear @0xtuytuy  I have made proper fixes

**Comment by 0xtuytuy** [comment]
image

@julabear for your reivew plz

**Comment by julabear** [comment]
Looks good from the screenshot... bit difficult to judge / need to see zoomed in / IRL

**Comment by Dan1618** [comment]
@julabear  how big zoom do you need? here is 150%

image

**Comment by julabear** [comment]
Looks good :) Thans!

**Review by 0xtuytuy — APPROVED** [review]
LGTM

**Pull request merged**
